[package]
name = "tui-chat-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
ed25519-dalek.workspace = true
hkdf = "0.12.4"
rand.workspace = true
rand_core.workspace = true
postcard.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tui-chat-protocol = { path = "../protocol" }
uuid.workspace = true
vodozemac.workspace = true
x25519-dalek = { version = "3.0.0", features = ["static_secrets"] }
zeroize.workspace = true

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints]
workspace = true
